M48
; DRILL file {KiCad 7.0.10} date Wed Feb 28 12:36:17 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-28T12:36:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.2Y-2.1
X6.6Y-0.7
X7.3Y-1.7
X10.4Y-0.7
X10.4Y-2.8
M30
