M48
; DRILL file {KiCad 7.0.10} date Wed Feb 28 13:58:59 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-28T13:58:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.7Y-2.8
X5.7Y-3.1
X5.7Y-3.6
X5.7Y-3.7
X5.9Y-2.8
X5.9Y-3.0
X5.9Y-3.6
X6.0Y-2.8
T2
X5.9Y-3.1
X5.9Y-3.2417
T3
X5.7Y-3.2984
X5.7Y-3.3984
X5.7Y-3.4984
M30
