M48
; DRILL file {KiCad 7.0.10} date Wed Mar  6 13:01:37 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-06T13:01:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.5Y-2.9
X6.3Y-4.8
X6.4Y-2.1
X8.3Y-3.7
X9.0Y-2.1
M30
